# Generated by Django 5.1.8 on 2026-06-16 13:47

import django.core.validators
import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DellScanRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('targets', models.TextField()),
                ('idrac_username', models.CharField(blank=True, max_length=128)),
                ('idrac_password', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.devicerole')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Dell scan range',
                'verbose_name_plural': 'Dell scan ranges',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DellServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('idrac_address', models.CharField(max_length=255)),
                ('idrac_username', models.CharField(blank=True, max_length=128)),
                ('idrac_password', models.TextField(blank=True)),
                ('service_tag', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('bios_version', models.CharField(blank=True, max_length=64)),
                ('idrac_firmware', models.CharField(blank=True, max_length=64)),
                ('health', models.CharField(blank=True, default='unknown', max_length=20)),
                ('sync_status', models.CharField(default='new', max_length=30)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_message', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dell_server', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Dell server',
                'verbose_name_plural': 'Dell servers',
                'ordering': ('device',),
            },
        ),
        migrations.CreateModel(
            name='DellComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('component_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('serial', models.CharField(blank=True, max_length=128)),
                ('part_number', models.CharField(blank=True, max_length=128)),
                ('firmware', models.CharField(blank=True, max_length=64)),
                ('capacity_bytes', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('health', models.CharField(blank=True, default='unknown', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='netbox_idrac_inventory.dellserver')),
            ],
            options={
                'verbose_name': 'Dell component',
                'verbose_name_plural': 'Dell components',
                'ordering': ('server', 'component_type', 'name'),
                'constraints': [models.UniqueConstraint(fields=('server', 'component_type', 'name'), name='netbox_idrac_inventory_dellcomponent_unique_per_server')],
            },
        ),
    ]
