# Generated by Django 6.0.6 on 2026-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_idrac_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dellserver',
            name='site_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
